2024-08-01 16:02:13,946 INFO    MainThread:14220 [wandb_init.py:_log_setup():292] Logging user logs to D:\youssef\on-policy\onpolicy\scripts\results\SwarmEnv\mappo\check\wandb\run-20240801_160213-1yurltd3\logs\debug.log
2024-08-01 16:02:13,947 INFO    MainThread:14220 [wandb_init.py:_log_setup():293] Logging internal logs to D:\youssef\on-policy\onpolicy\scripts\results\SwarmEnv\mappo\check\wandb\run-20240801_160213-1yurltd3\logs\debug-internal.log
2024-08-01 16:02:13,947 INFO    MainThread:14220 [wandb_setup.py:_flush():68] setting env: {}
2024-08-01 16:02:13,947 INFO    MainThread:14220 [wandb_setup.py:_flush():68] setting user settings: {}
2024-08-01 16:02:13,947 INFO    MainThread:14220 [wandb_setup.py:_flush():68] multiprocessing start_methods=spawn
2024-08-01 16:02:17,567 INFO    MainThread:14220 [wandb_run.py:_console_start():1265] atexit reg
2024-08-01 16:02:17,567 INFO    MainThread:14220 [wandb_run.py:_redirect():1135] redirect: SettingsConsole.WRAP
2024-08-01 16:02:17,567 INFO    MainThread:14220 [wandb_run.py:_redirect():1166] Wrapping output streams.
2024-08-01 16:02:17,567 INFO    MainThread:14220 [wandb_run.py:_redirect():1182] Redirects installed.
2024-08-01 16:02:44,487 INFO    MainThread:14220 [wandb_run.py:_atexit_cleanup():1238] got exitcode: 0
2024-08-01 16:02:44,487 INFO    MainThread:14220 [wandb_run.py:_restore():1210] restore
2024-08-01 16:02:44,492 INFO    MainThread:14220 [wandb_run.py:_wait_for_finish():1349] got exit ret: uuid: "6b64979d8efe4d53b38e0a681628f534"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 1
    }
    pusher_stats {
      uploaded_bytes: 1600
      total_bytes: 1600
    }
  }
}

2024-08-01 16:02:46,496 INFO    MainThread:14220 [wandb_run.py:_wait_for_finish():1349] got exit ret: uuid: "99da0fea99694ec7919add4b78842ea7"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 5
      other_count: 2
    }
    pusher_stats {
      uploaded_bytes: 372709
      total_bytes: 372709
    }
  }
}

2024-08-01 16:02:48,500 INFO    MainThread:14220 [wandb_run.py:_wait_for_finish():1349] got exit ret: uuid: "2b3b9f00c7124de2bb0ac6d96b4d4a4e"
response {
  poll_exit_response {
    done: true
    exit_result {
    }
    file_counts {
      wandb_count: 5
      other_count: 2
    }
    pusher_stats {
      uploaded_bytes: 372709
      total_bytes: 372709
    }
  }
}

2024-08-01 16:02:49,576 INFO    MainThread:14220 [wandb_run.py:_show_files():1543] logging synced files
2024-08-01 16:02:49,607 INFO    MainThread:14220 [internal.py:handle_exit():137] Internal process exited
